"use client";
import { useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import QuizCard from "@/components/QuizCard";
import ProgressBar from "@/components/ProgressBar";
import { questionsByLevel } from "@/data/questions";
import { getLevel } from "@/data/levels";
import { calculateQuizScore } from "@/lib/score";
import { completeLevel } from "@/lib/progress";
export default function QuizPage() { const id=Number(useParams<{id:string}>().id); const level=getLevel(id); const questions=questionsByLevel[id]; const [index,setIndex]=useState(0); const [selected,setSelected]=useState<number>(); const [correct,setCorrect]=useState(0); const [checked,setChecked]=useState(false); const [result,setResult]=useState<number>(); if(!level||!questions)return <main className="p-10">关卡不存在</main>; const submit=()=>{ if(selected===undefined)return; setChecked(true); }; const next=()=>{ const finalCorrect=correct+(selected===questions[index].answer?1:0); if(index===questions.length-1){const score=calculateQuizScore(finalCorrect,questions.length);setResult(score);if(score>=80)completeLevel(id,level.xp);}else{setCorrect(finalCorrect);setIndex(i=>i+1);setSelected(undefined);setChecked(false);} }; if(result!==undefined){const pass=result>=80;return <main className="mx-auto max-w-xl px-5 py-16"><div className="glass rounded-3xl p-8 text-center"><div className="text-6xl">{pass?"🏆":"🔧"}</div><p className="eyebrow mt-5">MISSION REPORT</p><h1 className="mt-3 text-3xl font-black">{pass?"关卡通关！":"还差一点点"}</h1><div className={`mx-auto my-6 grid h-28 w-28 place-items-center rounded-full border-8 ${pass?"border-lime-300 text-lime-300":"border-amber-300 text-amber-300"}`}><strong className="text-3xl">{result}</strong></div><p className="text-slate-400">{pass?`获得 ${level.xp} XP，下一关已解锁。`:"需要达到 80 分，复习后再来挑战吧。"}</p><div className="mt-7 flex gap-3"><Link className="btn-secondary flex-1" href={`/lesson/${id}`}>复习课程</Link><Link className="btn-primary flex-1" href={pass?"/levels":`/quiz/${id}`}>{pass?"继续前进":"重新挑战"}</Link></div></div></main>} return <main className="mx-auto max-w-2xl px-5 py-12"><div className="mb-7 flex items-center justify-between"><div><p className="eyebrow">LEVEL {id} · FINAL QUIZ</p><h1 className="mt-2 text-2xl font-black">通关测验</h1></div><span className="font-bold text-cyan-200">{index+1} / {questions.length}</span></div><ProgressBar compact value={(index+1)/questions.length*100}/><div className="mt-6"><QuizCard question={questions[index]} selected={selected} onSelect={setSelected} checked={checked}/></div><button onClick={checked?next:submit} disabled={selected===undefined} className="btn-primary mt-5 w-full disabled:opacity-30">{checked?(index===questions.length-1?"查看成绩":"下一题 →"):"确认答案"}</button></main> }
