"use client";
import Link from "next/link";
import ProgressBar from "@/components/ProgressBar";
import { levels } from "@/data/levels";
import { getLearningLevel, pointsToNextLevel } from "@/lib/score";
import { nextLevelId } from "@/lib/progress";
import { useProgress } from "@/lib/useProgress";
export default function Home() { const { progress } = useProgress(); const current = levels[nextLevelId(progress.completedLevels)-1]; const percent = Math.round(progress.completedLevels.length / levels.length * 100); return <main><section className="relative overflow-hidden border-b border-cyan-300/10"><div className="absolute left-1/2 top-0 h-96 w-96 -translate-x-1/2 rounded-full bg-cyan-400/10 blur-3xl"/><div className="relative mx-auto grid max-w-6xl gap-10 px-5 py-16 md:grid-cols-[1.15fr_.85fr] md:py-24"><div><div className="eyebrow">TRAFFIC DATA QUEST · 智慧交通学习计划</div><h1 className="mt-5 text-5xl font-black leading-tight md:text-7xl">解锁城市脉络<br/><span className="bg-gradient-to-r from-cyan-300 to-lime-300 bg-clip-text text-transparent">让数据驱动通行</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-400">进入 16 片智慧城区，通过知识补给、互动任务与关卡测验，从数据新手成长为交通大数据专家。</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/levels" className="btn-primary">进入关卡地图 →</Link><Link href="/profile" className="btn-secondary">查看我的成就</Link></div></div><div className="glass rounded-[2rem] p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">驾驶员档案</p><h2 className="mt-2 text-2xl font-black">LEVEL {getLearningLevel(progress.points)} · 数据探索者</h2></div><div className="grid h-16 w-16 place-items-center rounded-2xl bg-gradient-to-br from-cyan-300 to-blue-500 text-3xl">🚘</div></div><div className="my-6 grid grid-cols-2 gap-3"><Stat label="总积分" value={`${progress.points} XP`} /><Stat label="距升级" value={`${pointsToNextLevel(progress.points)} XP`} /></div><ProgressBar value={percent} label="总学习进度"/><div className="mt-6 rounded-2xl border border-cyan-300/20 bg-cyan-300/5 p-5"><p className="text-xs text-slate-400">推荐继续</p><p className="mt-1 font-bold">{current.icon} 第 {current.id} 关 · {current.title}</p><Link href={`/lesson/${current.id}`} className="mt-4 inline-block text-sm font-bold text-cyan-300">启动任务 →</Link></div></div></div></section><section className="mx-auto max-w-6xl px-5 py-14"><div className="grid gap-5 md:grid-cols-3"><Feature icon="🗺️" title="城市闯关地图" text="沿智慧交通路线依次解锁 16 个主题关卡。"/><Feature icon="🎮" title="互动数据任务" text="匹配、代码拼图、预测与聚类，让算法真正动起来。"/><Feature icon="🏅" title="积分成就系统" text="通过测验累积 XP，收集你的交通数据徽章。"/></div></section></main> }
function Stat({label,value}:{label:string;value:string}) { return <div className="rounded-xl bg-white/5 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-black text-cyan-100">{value}</p></div> }
function Feature({icon,title,text}:{icon:string;title:string;text:string}) { return <div className="glass rounded-2xl p-6"><span className="text-3xl">{icon}</span><h3 className="mt-4 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div> }
